FROM centos:7
RUN yum install -y epel-release
# Install tools
RUN yum install -y net-tools tcpdump telnet curl 
# Install service
RUN yum install -y nginx 
#install supervisor
RUN yum install -y supervisor

COPY nginx/nginx.conf /etc/nginx/nginx.conf
RUN mkdir -p /etc/nginx/location.d/
RUN rm -f /etc/nginx/location.d/*

COPY suprevisor/nginx.ini /etc/supervisord.d/ 
CMD /usr/bin/supervisord -n
